export const siteConfig = {
  name: "CodeWinOptimizer",
  title:
    "CodeWinOptimizer - Free Windows Optimizer, Debloater & Tweak Tool for Windows 10/11",
  description:
    "Download CodeWinOptimizer, a free open-source Windows optimizer and debloater for Windows 10 & 11. Install 181 apps via WinGet or Chocolatey, apply 140+ registry & performance tweaks, clean disk space, manage startup and create restore points — all from one portable .exe. A WinUtil-style utility without telemetry.",
  url:
    process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ||
    "https://codewinoptimizer.com",
  logo: "/logo.png",
  repository: "https://github.com/oscarxdev/CodeWinOptimizer-App",
  releases: "https://github.com/oscarxdev/CodeWinOptimizer-App/releases",
  author: "OscarDev",
  twitterHandle: "@OscarDev",
  keywords: [
    "CodeWinOptimizer",
    // Brand / category
    "Windows optimizer",
    "Windows optimization",
    "optimize Windows",
    "optimize Windows 10",
    "optimize Windows 11",
    "Windows 10 optimizer",
    "Windows 11 optimizer",
    "Windows debloater",
    "debloat Windows",
    "debloat Windows 10",
    "debloat Windows 11",
    "remove bloatware",
    "remove preinstalled apps",
    "remove Windows bloatware",
    "speed up Windows",
    "make Windows faster",
    "faster boot Windows",
    "Windows performance",
    "Windows performance tweaks",
    "Windows performance tuning",
    "Windows tweaks",
    "Windows 11 tweaks",
    "Windows 10 tweaks",
    "Windows system tweaks",
    "Windows registry tweaks",
    "registry tweaks",
    "Windows privacy",
    "Windows privacy tweaks",
    "disable telemetry",
    "disable Windows telemetry",
    "stop Windows tracking",
    "disable Cortana",
    "Windows cleanup",
    "Windows cleanup tool",
    "clean temp files",
    "free up disk space Windows",
    "disk cleanup",
    "Windows startup manager",
    "disable startup programs",
    "Windows startup slow",
    "system restore point",
    "Windows repair tool",
    "SFC DISM scan",
    "Windows Update manager",
    "winget",
    "winget install apps",
    "chocolatey",
    "install apps Windows",
    "Windows package manager",
    "Microsoft Store apps uninstall",
    "winutil",
    "WinUtil alternative",
    "WinUtil for Windows",
    "Windows utility",
    "Windows debloat script GUI",
    "PC optimizer",
    "PC health check",
    "gaming performance Windows",
    "gaming tweaks Windows",
    "network tweaks Windows",
    "latency tweaks",
    "disable Nagle",
    "O&O ShutUp10++",
    "portable Windows app",
    "portable PC optimizer",
    "open source Windows tool",
    "Windows 11 speed up",
    "Windows 10 speed up",
    "maintenance Windows",
    // Spanish
    "optimizar Windows",
    "optimizador de Windows",
    "Windows 10 optimizar",
    "Windows 11 optimizar",
    "acelerar Windows",
    "hacer Windows más rápido",
    "quitar bloatware",
    "desinstalar apps preinstaladas",
    "desactivar telemetría",
    "mejorar rendimiento Windows",
    "ajustes de Windows",
    "limpiar Windows",
    "limpiador de Windows",
    "gestor de inicio de Windows",
    "alternativa a WinUtil",
    "utilidad de Windows",
    "optimización de Windows gratis",
  ],
  features: [
    "System restore points & registry backup",
    "Install/uninstall 181 apps via WinGet or Chocolatey",
    "140+ registry, privacy & performance tweaks",
    "Windows features (Hyper-V, WSL, Sandbox, .NET)",
    "Startup manager (reversible, Task-Manager-compatible)",
    "Disk cleanup & quick fixes (SFC/DISM, network reset)",
    "System monitor with PC Health Score",
    "Portable single .exe for Windows 10/11",
  ],
};

export function absoluteUrl(path = "") {
  if (/^https?:\/\//.test(path)) return path;
  return `${siteConfig.url}${path.startsWith("/") ? path : `/${path}`}`;
}
